### ISSUE TITLE
Suggestions : Recherche dans le titre & Indexation des décisions de l'INPI

### ISSUE THREAD

**Issue by joachimBrindeau** [Cour-de-cassation/judilibre-search#104]
Bonjour,

Je ne sais pas si c'est le bon endroit pour faire des retours d'expérience mais voici deux suggestions.

**Recherche dans le titre :**
Serait-il possible de faire des recherches par titre avec un argument comme `intitle:` ?

La majorité du temps on recherche une JP avec un numéro de rôle et une cour d'appel.
Sauf que là, on retrouve près de 5 000 résultats plutôt que 1 (ou 0) :
![Capture d’écran 2022-06-22 à 17 51 36](https://user-images.githubusercontent.com/6870905/175076633-778bd964-6495-4a93-9b1d-068b7e9d5b4d.png)

**Indexation décisions INPI :**
Si je peux me permettre une suggestion qui ne relève pas des fonctionnalités existantes, ce serait super d'intégrer les décisions de l'INPI (litiges sur des marques, brevets, etc.). Elles font l'objet de recours devant la cour d'appel mais ne sont pas répertoriées par légifrance.

Le seul site qui les référence est archaïque : [https://base-jurisprudence.inpi.fr/cindocwebjsp/](https://base-jurisprudence.inpi.fr/cindocwebjsp/)
Le [fichier stock](https://www.inpi.fr/open-data-jurisprudence-et-decisions-d-opposition) fait 7go et est mis à jour mensuellement (40 mo).

Merci pour cet outil !
Bonne journée

**Comment by SebCourvoisier** [comment]
Bonjour,

L'intitulé d'un arrêt est une information élaborée pour l'affichage des résultats et n'est pas requêtable en lui-même. Cependant il est possible de combiner une recherche par numéro RG (qui n'est pas un identifiant) et le siège de la cour d'appel (filtre disponible sous le champ de saisie). Sachant que seule la combinaison numéro RG + siège + date de rendu est susceptible de ne retourner qu'un seul résultat.

Il n'est pas prévu à ce jour d'intégrer les décisions de l'INPI.

**Comment by joachimBrindeau** [comment]
Bonjour,

Merci pour cette réponse, je viens de comprendre d'où vient le nombre de résultats.
Rechercher le numéro RG `15/08112` me sort toutes les décisions avec le chiffre 15.
Si je tape `"15/08112"` j'ai le résultat que je recherche.
Peut-être à rectifier car ce n'est pas très intuitif pour l'utilisateur.

Bonne journée !
