### ISSUE TITLE
Add cloud ready healthcheck endpoints

### ISSUE THREAD

**Issue by rhanka** [Cour-de-cassation/judilibre-search#12]
Readiness and Liveness should be implemented in addition to healthcheck for enabling auto healing of service
Some libs:
https://www.npmjs.com/package/@cloudnative/health
https://www.npmjs.com/package/express-actuator

**Comment by SebCourvoisier** [comment]
@rhanka The current healthcheck relies on curl, but curl is not available in the image (and I still don't know how to install it properly).

**Comment by rhanka** [comment]
livenessprobe implemented now through judilibre-admin
