### ISSUE TITLE
Impossible de modifier l'API

### ISSUE THREAD

**Issue by diouck** [Cour-de-cassation/judilibre-search#120]
Bonjour
Comme indiqué, j'essaye de modifier l'accès à l'API mais la case est inaccessible pour l'activer.
Avez vous une idée? 
Merci
![image](https://user-images.githubusercontent.com/3952114/194878819-4f7192f6-21f4-4714-9e6b-b2f22883328f.png)

**Comment by SebCourvoisier** [comment]
Bonjour, 
Il s'agit d'un sujet propre à l'interface de PISTE, je vous invite donc à vous adresser à leur support utilisateur : https://developer.aife.economie.gouv.fr/support/#/

**Comment by diouck** [comment]
Merci C OK pour moi
