### ISSUE TITLE
Recherche par numéro de décision

### ISSUE THREAD

**Issue by MetallianFR68** [Cour-de-cassation/judilibre-search#38]
Sauf erreur de ma part, il n'y a pas de méthode de recherche par numéro de décision.

Or nous, les juristes, utilisons beaucoup ce critère.
Par exemple quand un avocat cite une jurisprudence de la cour de cassation il indique toujours le numéro type 20.12-234

Serait-il possible de rajouter ce paramètre ?

**Comment by MetallianFR68** [comment]
Je ne sais pas si c'est moi qui avais mal regardé ou si quelque chose a changé mais la recherche sur numéro de pourvoi fonctionne.
On peut clore cet "issue"

**Comment by rhanka** [comment]
Merci de votre implication !
