### ISSUE TITLE
Pourquoi n'avoir pas utilisé l'API Legifrance

### ISSUE THREAD

**Issue by Gotfers** [Cour-de-cassation/judilibre-search#40]
Bonjour,
Pourquoi la Cour de cassation ne s'est pas rapproché de la DILA pour utiliser l'API Legifrance et le fonds "JURI"... quelle est l'utilité de deux API distinctes ?

**Comment by rhanka** [comment]
La Cour travaille toujours avec la DILA, et y diffuse ses contenus.
Le fonds diffusé par l'API Judilibre correspond plutôt au fonds "CASS", le reprend et est amené à le substituer à terme, et à devenir exhaustif progressivement sur l'ordre judiciaire. L'API légifrance devrait elle même requêter l'API judilibre, à terme, probablement.
L'API Judilibre dispose d'une taxonomie plus détaillée par rapport à la matière des décisions judiciaire (zonage, judiriction, chambre formation), qui est son champ de spécialité.
Pour parcourir le modèle :
https://developer.aife.economie.gouv.fr/index.php?option=com_apiportal&view=apitester&usage=api&apitab=tests&apiName=JUDILIBRE&apiId=2cd0b969-d459-4f27-83f4-f3e9a3fd5dae&managerId=2&type=rest&apiVersion=1.0.0&Itemid=265&swaggerVersion=2.0&lang=fr
