### ISSUE TITLE
Quelles juridictions dans JUDILIBRE ?

### ISSUE THREAD

**Issue by MetallianFR68** [Cour-de-cassation/judilibre-search#44]
Bonjour,

Voici le calendrier fixé par le décret : 

30 Septembre 2021 : décisions du Conseil d'Etat et de la Cour de Cassation
31 Mars 2022 : Cours administratives d'appel
30 Avril 2022 : Cours d'appel en matière civile, sociale et commerciale
30 Juin 2022 : Tribunaux Administratifs de première instance
30 Juin 2023 : Conseils des prud'hommes
31 Décembre 2024 : Tribunaux de commerce et Tribunaux judiciaires en matière pénale
30 Septembre 2025 : Tribunaux Judiciaires en matière civile
31 Décembre 2025 : Cours d'assises et Cours d'appel en matière pénale

Au 30/09, il était donc aussi prévu l'opendata des décisions du Conseil d'Etat.
On ne les trouve cependant pas sur JUDILIBRE.

Celles-ci ont elle vocation à être intégrées dans JUDILIBRE ?

Au final, quelles sont les juridictions dont on peut espérer trouver les décisions sur JUDILIBRE au cours des prochains mois ?

Bien cordialement

**Comment by rhanka** [comment]
Les décisions du conseil d'état n'ont - à ce jour - pas été prises en compte dans l'API judilibre, qui se focalise sur le judiciaire, elles sont disponibles ici : https://opendata.conseil-etat.fr/ - comme vous le verrez les données du conseil d'Etat sont en xml et fournies sans API.

La modélisation des données des systèmes sources est actuellement importante, et la gouvernance associée - complexe. A ce stade sont **exclues** donc de judilibre: 
- 31 Mars 2022 : Cours administratives d'appel
- 30 Juin 2022 : Tribunaux Administratifs de première instance


Ainsi les prochaines échéances pour l'API judilibre et l'ordre judiciaire sont 
- 30 Avril 2022 : Cours d'appel en matière civile, sociale et commerciale
- 30 Juin 2023 : Conseils des prud'hommes
- 31 Décembre 2024 : Tribunaux de commerce
- 31 Décembre 2024 : Tribunaux judiciaires en matière pénale
- 30 Septembre 2025 : Tribunaux Judiciaires en matière civile
- 31 Décembre 2025 : Cours d'assises et Cours d'appel en matière pénale
