### ISSUE TITLE
Add log lib, compatible with Kube environment

### ISSUE THREAD

**Issue by rhanka** [Cour-de-cassation/judilibre-search#5]
For stateless logging, API-compliant lib should be used.
Opentracing meets this API sent log requirement, compatible with Kube/Openshift
This seems to be the well-maintained lib: https://www.npmjs.com/package/opentracing (1M dl/week)

**Comment by SebCourvoisier** [comment]
@rhanka: Regarding Opentracing (https://github.com/opentracing/opentracing-javascript/issues/143): _« It is in maintenance mode. Active development moved to https://github.com/open-telemetry/opentelemetry-js »_ (but OpenTelemetry does not seem to be production ready yet...)

The Opentracing lib does not provide any tracer. Some articles talk about using the Jaeger tracer (https://github.com/jaegertracing/jaeger-client-node) for k8s monitoring.

**Comment by rhanka** [comment]
Un bon vieu log en text serait déjà suffisant, nous loggons via fluent bit le contenu du conteneur à chaque nouvel événement et ip client, il y a donc le tag date à chaque event. un json line pour les événement serait plus pratique

**Comment by rhanka** [comment]
Logs added with express #43
