### ISSUE TITLE
Stock des décisions antérieures à l'opendata

### ISSUE THREAD

**Issue by MetallianFR68** [Cour-de-cassation/judilibre-search#83]
Selon mes informations, divers responsables indiquent que l'obligation de publier en opendata ne débute qu'à la date indiquée dans l'arrêté du 28/04/2021

En résumé, le stock des anciennes décisions antérieures à la date indiquée dans l'arrêté n'a aucune obligation d'être fournie.

C'est ce que semble faire le Conseil d'Etat qui ne fournit les infos que depuis le 30/09/2021

A contrario la Cour de Cassation est "mieux disante" puisqu'elle a fourni spontanément tout le stock antérieur

Que peut-on espérer des Cours d'Appel au 30/04/2022 ?
Aurons-nous le stock antérieur ?

En vous remerciant par avance pour votre réponse.

**Comment by SebCourvoisier** [comment]
Bonjour,

Le stock antérieur sera rendu disponible suivant le chaînage des décisions (par exemple, si une décision de la Cour de cassation nouvellement publiée vient attaquer un arrêt de cour d'appel public archivé dans le stock, alors cet arrêt sera à son tour indexé et publié dans Judilibre).
