### ISSUE TITLE
Erreur de date dans certaines décisions de Cours d'appel

### ISSUE THREAD

**Issue by TaniaBDev** [Cour-de-cassation/judilibre-search#98]
Certaines décisions ont des erreurs de date. 

Par exemple, pour ces décisions de la Cour d'appel de Versailles, la date de décision dans API et dans le titre est 23 mai 2022, mais la date d'arrêt dans le corps de décisions est autre :
628c7661dfcf1305b332f280 - 04/04/2022
628c765fdfcf1305b332f27e - 16/05/2022
628c765fdfcf1305b332f27c - 16/05/2022
628c765cdfcf1305b332f278 - 16/05/2022

C'est possible qu'il y en a d'autres.

**Comment by SebCourvoisier** [comment]
S'agissant du premier exemple (628c7661dfcf1305b332f280), la date de rendu est bien le 23 mai 2022, tel qu'il est écrit en toutes lettres dans le corps de la décision : "LE VINGT-TROIS MAIL _[sic]_ DEUX MILLE VINGT DEUX, La cour d'appel de Versailles a rendu l'arrêt suivant...".

Il en va de même pour les arrêts 628c765fdfcf1305b332f27e, 628c765fdfcf1305b332f27c et 628c765cdfcf1305b332f278.

L'autre date mentionnée dans le ticket concerne une décision antérieure concernant l'affaire ou bien constitue une erreur de rédaction à la source.

**Comment by TaniaBDev** [comment]
Merci pour votre réponse. 

En effet, je n'ai pas vérifié dans le corps de décisions mais regardé uniquement les dates "Arrêt du XXX" dans l'entête.
