### ISSUE TITLE
Des appels rapprochés sur les statistiques globales des APIs donnent 2 résultats différents

### ISSUE THREAD

**Issue by atomobianco** [Cour-de-cassation/judilibre-search#99]
Les requêtes au endpoint `/stats` donnent **arbitrairement** deux résultats différents
```
{
  "indexedTotal": 599428,
  ...
```
ou
```
{
  "indexedTotal": 399985,
  ...
```

**Comment by SebCourvoisier** [comment]
Non reproductible. Peut-être lié à des opérations de nettoyage/réindexation en cours.
